### PR TITLE
fix: title move position

### LINKED ISSUE #13143: Hovering over a dashboard tile with a title that spans 2 lines makes the title move position
Screenshot 2025-01-07 at 22 56 56

You can see here that it expands upwards, coming out of the tile. 
The position of the title should not change on hover, you should just be able to see the part that is hidden.

### PR DESCRIPTION
**Pull request by ptdatta**
Closes: 
Fixes #13143 

### Description:

Before:
[Screencast from 09-01-25 01:23:34 PM IST.webm](https://github.com/user-attachments/assets/37e4c26e-97fd-4b80-a9a8-0be3081ca4ff)

After:
[Screencast from 09-01-25 01:22:26 PM IST.webm](https://github.com/user-attachments/assets/790e1020-4772-4319-828a-0aa858ee4a7b)

### Reviewer actions

- [ ] I have manually tested the changes in the preview environment
- [ ] I have reviewed the code
- [ ] I understand that "request changes" will block this PR from merging

### CODE REVIEW

File: packages/frontend/src/components/DashboardTiles/TileBase/index.tsx [hunk 1]
```diff
@@ -135,6 +135,7 @@ const TileBase = <T extends Dashboard['tiles'][number]>({
                 $isEditMode={isEditMode}
                 $isEmpty={isMarkdownTileTitleEmpty || hideTitle}
                 style={{
+                    display: 'inline-block',
```
Comment (magnew) [inline packages/frontend/src/components/DashboardTiles/TileBase/index.tsx:138]: This breaks this layout for the action items in the tiles. 

Example:
Screenshot 2025-01-14 at 11 08 41

And:
Screenshot 2025-01-14 at 11 09 04

Keep in mind that this is a flex layout.

**Review by magnew — CHANGES_REQUESTED** [review]
As is this breaks the layout

**Review by magnew — COMMENTED** [review]
I added a fix. Will merge when tests pass.

**Review by magnew — APPROVED** [review]
Looks good, I will merge. 

@ptdatta Thank you for contributing!
