### PR TITLE
fix: extract first and last name from OIDC profile JSON

### LINKED ISSUE #17601: SSO users show blank profile name and avatars after OIDC login
When users sign in through our internal OIDC provider, Lightdash displays “undefined” for the profile avatar and leaves the first/last name empty.

The IdP is sending `given_name` and `family_name` in the ID token, but Lightdash only reads the top-level Passport fields and never reaches the raw claims.

The fix is to read the names from the `_json` token payload and fall back to initials from the email so every SSO user gets a sensible display name and avatar.

### PR DESCRIPTION
**Pull request by notgiorgi**
Closes #17601

### Description:

Enhances OIDC authentication by improving profile data extraction. The PR adds support for retrieving user's first name and last name from the `_json` object in the profile, which is a common location for these fields in OIDC responses. This ensures more reliable user information extraction across different OIDC providers.

### CODE REVIEW

**Comment by notgiorgi** [comment]
* **#17597** <a href="https://app.graphite.dev/github/pr/lightdash/lightdash/17597?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/lightdash/lightdash/17597?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: packages/backend/src/controllers/authentication/strategies/oidcStrategy.ts [hunk 1]
```diff
@@ -23,7 +23,13 @@ export const isGenericOidcPassportStrategyAvailableToUse =
     lightdashConfig.auth.oidc.metadataDocumentEndpoint;
 
 const createOpenIdUserFromProfile = (
-    profile: PassportProfile,
+    profile: PassportProfile & {
+        _json?: {
+            given_name?: string;
+            family_name?: string;
+            [key: string]: unknown;
+        };
```
Comment (notgiorgi) [inline packages/backend/src/controllers/authentication/strategies/oidcStrategy.ts:31]: https://github.com/jaredhanson/passport-openidconnect/blob/master/lib/strategy.js#L214-L224

**Comment by notgiorgi** [comment]
### Merge activity

* **Oct 23, 8:20 AM UTC**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/lightdash/lightdash/17597).
* **Oct 23, 8:21 AM UTC**: @notgiorgi merged this pull request with [Graphite](https://app.graphite.dev/github/pr/lightdash/lightdash/17597).
